### ISSUE TITLE
[Feature Request] Custom decks?

### ISSUE THREAD

**Issue by Firgof** [reonZ/pf2e-hero-actions#1]
I have a full deck of custom hero action cards that I'd love to use and, even though I'm copying the structure and data, the module appears to be overwriting my custom table with its internal list of cards.

Would it be possible for it to be told to draw from a different compendium of cards?

**Comment by reonZ** [comment]
I will look into it.

**Comment by reonZ** [comment]
I have a `2.0.0` on the work which will allow custom actions and tables to be used, this is not finalized yet.

**Comment by reonZ** [comment]
2.0.0 is now released, i have done as much testing as i could to ensure retro-compatibility but the module was basically redone from scratch.
