### ISSUE TITLE
Await actor update in useHeroAction

### ISSUE THREAD

**Issue by Larkinabout** [reonZ/pf2e-hero-actions#10]
Getting the hero points value after calling `useHeroAction` results in the wrong value. Please can an await be added to this line?: https://github.com/reonZ/pf2e-hero-actions/blob/e7766096f3421ea5400ea2d283d426107adc95be/src/actions.ts#L54

**Comment by reonZ** [comment]
What situation requires you to do that ? Normally you would not have to manually get them, you should be working with the `updateActor` or `renderCharacterSheetPF2e` hooks.

**Comment by Larkinabout** [comment]
Good shout. I was planning to manually trigger an update of the HUD following the `useHeroAction` call, but actually I can forgo the manual part and just let it trigger off the `updateActor` instead.
