### ISSUE TITLE
Hero Action on Character Sheet Misaligned

### ISSUE THREAD

**Issue by xKillerbees** [reonZ/pf2e-hero-actions#11]
![image](https://github.com/reonZ/pf2e-hero-actions/assets/2941079/db4d8f0f-a932-4c01-bbc1-94eb0d02c86b)
Is this the intended formatting for hero actions? Should it align like the below Actions section? I've disabled my UI module and it still does this.

**Comment by reonZ** [comment]
fixed in `2.8.0`
