### ISSUE TITLE
Trading?

### ISSUE THREAD

**Issue by LionheadGaming** [reonZ/pf2e-hero-actions#2]
Outstanding module, really well done, and extremely useful. Love the custom decks. 

Something I like to allow at my table is the trading of Hero Point Cards, do you think that's something you'd be able and willing to support with your excellent module?

**Comment by reonZ** [comment]
I am glad that you like it.

As for your request, i will look into it, it is definitely doable, i just need to see how it should be done.

Do you have any advice on the whole trading process ? should a player select their own action and the action they want, and the request be sent to the other player who can accept ? Or maybe it should be something only the GM can do via a macro for instance ?

**Comment by LionheadGaming** [comment]
I'd opt for the former and just make sure its known to the GM somehow that a trade has occurred and what was given to who.

**Comment by reonZ** [comment]
With version `2.2.0`, characters can now trade with each others.
