### ISSUE TITLE
Integration with Token Action HUD

### ISSUE THREAD

**Issue by moulson1313** [reonZ/pf2e-hero-actions#4]
Is there a way that the card section of the character sheet could be added to the Token Action HUD so that players could access the cards they have quickly? (not a bug but a feature request)

**Comment by reonZ** [comment]
This should be something to ask to the people who are making `Token Action HUD`, all they have to do is access the data on the actor, it is in the flags.

I wouldn't even know where to start and would have to parse all their source code if i had to do on my end.

**Comment by moulson1313** [comment]
Thank you, I will.

**Comment by reonZ** [comment]
So, to make things a bit easier, i exposed 2 functions in the api of the module.
