### ISSUE TITLE
Allow toggling chat output?

### ISSUE THREAD

**Issue by Janonas** [reonZ/pf2e-hero-actions#5]
A setting to toggle chat output would be nice.

**Comment by reonZ** [comment]
You mean for the regular `draw`, `discard` and `use` ?

**Comment by Janonas** [comment]
Yes, though we are a non native english speaker, and we once mistook a drawing of the action for playing of the action. Maybe an option would help people from having similliar troubles? i see that its not a huge issue and thats it could be abusable, maybe asetting (default, only shown draws and discard without the specific action with playing being regular, only display playing action) could work better?

**Comment by reonZ** [comment]
If you know how to fork a project on github, you could actually provide a translation for your language, all my modules are completely localized and ready to be translated.

If you dunno how to do it, we could set up something together where you provides me with the translations and i do the localization myself.

The file with all the localization can be found [here](https://github.com/reonZ/pf2e-hero-actions/blob/master/lang/en.json) if you are interested.

**Comment by reonZ** [comment]
I am gonna close this since you have not given any news, you are still free to provide localization for your language whenever you want though.
