### ISSUE TITLE
Allow cards to be drawn privately

### ISSUE THREAD

**Issue by mxvs** [reonZ/pf2e-hero-actions#8]
Hello

The official rules for the Hero Action deck state:

_"Whenever the GM would give you a Hero Point, including the one granted at the start of each session, draw a card from the deck instead. **Don’t reveal the card to the other players until you play it**."_

Currently the module has no option to draw the cards privately, I understand its always possible for players to set their roll mode to private first, but this requires them to toggle whenever they want to draw a card. Would it be possible to add an option in the module to draw the cards privately by default (as per the official rules)? 

Thanks!

**Comment by reonZ** [comment]
you probably gonna want to disable `trade` as well then.
