### ISSUE TITLE
The card can not be used or opened to read

### ISSUE THREAD

**Issue by 1RMR1** [reonZ/pf2e-hero-actions#9]
Hello,

I can draw the card fine. When I try to use it or read the description by clicking the name of the card I get this error.
pf2e-hero-actions.details.missing

I tried uninstalling and re installing it. I am on Foundry 11 as well.

Cheers,

**Comment by reonZ** [comment]
Could you show me the full error from the console please ?

**Comment by 1RMR1** [comment]
Hello,

That is the only error on the console that I see. Or I'm missing something. I tried to delete everything and reinstall this even the do not delete in the roll tables. It's now working fine so I can't reproduce the error.

**Comment by reonZ** [comment]
You missed the part that told you to clean the actions from the actors most likely.

Go in the compendium and look for the `Remove Hero Actions` macro and run it while leaving everything selected.

![image](https://github.com/reonZ/pf2e-hero-actions/assets/651462/7819a9df-3146-499d-b544-90c50c11593c)

**Comment by reonZ** [comment]
I will assume that this is fixed
